/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Editor;

import compilador.Calc1i;
import compilador.ParseException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextPane;

/**
 *
 * @author happy_000
 */
public class EditorTexto extends javax.swing.JFrame {

    /**
     * Creates new form EditorTexto
     */
    JTabbedPaneCloseButton tabs = new JTabbedPaneCloseButton();
    Calc1i parser = null;
         
    
    public EditorTexto() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setLayout(null);
        tabs.setSize(730, 530);
        tabs.setLocation(1,92);
        this.getContentPane().add(tabs);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        Ejecutar = new javax.swing.JButton();
        Debugger = new javax.swing.JButton();
        Reporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        GuardarC = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Buscar = new javax.swing.JMenuItem();
        Reemplazar = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        TErrores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));

        Ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editor/Iconos/Ejecutar.png"))); // NOI18N
        Ejecutar.setBorder(null);
        Ejecutar.setBorderPainted(false);
        Ejecutar.setContentAreaFilled(false);
        Ejecutar.setFocusPainted(false);
        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });

        Debugger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editor/Iconos/Depurar.png"))); // NOI18N
        Debugger.setBorder(null);
        Debugger.setBorderPainted(false);
        Debugger.setContentAreaFilled(false);
        Debugger.setFocusPainted(false);
        Debugger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebuggerActionPerformed(evt);
            }
        });

        Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editor/Iconos/Reporte.png"))); // NOI18N
        Reporte.setBorder(null);
        Reporte.setBorderPainted(false);
        Reporte.setContentAreaFilled(false);
        Reporte.setFocusPainted(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ejecutar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Debugger");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Reporte de Errores");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Velocidad de Debugger");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ejecutar)
                        .addGap(44, 44, 44)
                        .addComponent(Debugger)
                        .addGap(65, 65, 65)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Reporte)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Debugger)
                    .addComponent(Ejecutar)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reporte))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSlider1.getAccessibleContext().setAccessibleName("VDepurar");
        Ejecutar.getAccessibleContext().setAccessibleName("Ejecutar");
        Debugger.getAccessibleContext().setAccessibleName("Depurar");
        Reporte.getAccessibleContext().setAccessibleName("ReporteE");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setText("Archivo");

        Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jMenu1.add(Nuevo);

        Abrir.setBackground(new java.awt.Color(204, 204, 204));
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu1.add(Abrir);

        Guardar.setBackground(new java.awt.Color(153, 153, 153));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(Guardar);

        GuardarC.setBackground(new java.awt.Color(102, 102, 102));
        GuardarC.setText("Guardar Como");
        GuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCActionPerformed(evt);
            }
        });
        jMenu1.add(GuardarC);

        jMenuBar1.add(jMenu1);

        jMenu2.setLabel("Herramientas");

        Buscar.setBackground(new java.awt.Color(153, 153, 153));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jMenu2.add(Buscar);

        Reemplazar.setBackground(new java.awt.Color(102, 102, 102));
        Reemplazar.setText("Reemplazar");
        jMenu2.add(Reemplazar);

        jMenuItem9.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setText("Tabla de Simbolos");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Errores");

        TErrores.setBackground(new java.awt.Color(255, 255, 255));
        TErrores.setText("Tabla de Errores ");
        jMenu3.add(TErrores);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
     JTextPane textPane = new JTextPane();
        JScrollPane scrollPane = new JScrollPane(textPane);
        TextLineNumber tln = new TextLineNumber(textPane);
        scrollPane.setRowHeaderView( tln );
        tabs.add("Nuevo",scrollPane);
        tabs.setSelectedIndex(tabs.getTabCount()-1);
        
           
        
    }//GEN-LAST:event_NuevoActionPerformed

    private void DebuggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebuggerActionPerformed
        
   
    }//GEN-LAST:event_DebuggerActionPerformed
    public void Parsear(String entrada)throws ParseException{
        InputStream stream = new ByteArrayInputStream(entrada.getBytes(StandardCharsets.UTF_8));
         
        if(parser == null){
             parser = new Calc1i(stream);
         }
         else{
             Calc1i.ReInit(stream);
         }
        try { switch (Calc1i.one_line()){//call to grammar start symbol
              case -1: System.out.println("Error");
              case 0: break;
              case 1:  // result is stored on top of stack
                int x = ((Integer) Calc1i.argStack.pop()).intValue();
                System.out.println("Total = " + x);
                break;
          }
        } catch (ParseException x) {
        System.out.println("Exiting."); throw x;
        }
    }
    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
          
         JTextPane text = (JTextPane) ((JScrollPane) ((JTabbedPaneCloseButton.CloseButtonTab) tabs.getTabComponentAt(tabs.getSelectedIndex()).getComponentAt(0, 0)).tab).getViewport().getComponent(0);
         String entrada = text.getText()+"\n";
        try {
            Parsear(entrada);
        
        } catch (ParseException ex) {
            Logger.getLogger(EditorTexto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EjecutarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BuscarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        StringBuffer buffer;
        buffer = new StringBuffer();
        int result= jFileChooser.showOpenDialog(this);
        if(result==JFileChooser.APPROVE_OPTION)
        {
        try {
            FileReader reader;
            File file=jFileChooser.getSelectedFile();
            String nombre = file.getName();
            String dir1 = file.getPath();
            reader=new FileReader(file);
            int i=1;
            while(i!=-1)
            {
                i=reader.read();
                char ch=(char) i;
                buffer.append(ch);
            }
            buffer.deleteCharAt(buffer.length()-1);
            JTextPane textPane = new JTextPane();
            textPane.setText(buffer.toString());
            JScrollPane scrollPane = new JScrollPane(textPane);
            TextLineNumber tln = new TextLineNumber(textPane);
            scrollPane.setRowHeaderView( tln );
            tabs.addTab(nombre,scrollPane,dir1);
            tabs.setSelectedIndex(tabs.getTabCount()-1);
          
    
            
        }catch (FileNotFoundException ex) {
        }catch (IOException ex) {
        }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCActionPerformed
        // TODO add your handling code here:
     
        try
        {
            JTabbedPaneCloseButton.CloseButtonTab as = (JTabbedPaneCloseButton.CloseButtonTab) tabs.getTabComponentAt(tabs.getSelectedIndex()).getComponentAt(0, 0);
            JScrollPane ax = (JScrollPane) as.tab;
            JTextPane text = (JTextPane) ax.getViewport().getComponent(0);
      
            JFileChooser file=new JFileChooser();
            file.showSaveDialog(this);
            File guarda =file.getSelectedFile();
            String nombre=guarda.getName();
  if(guarda !=null)
  {
    FileWriter  save = new FileWriter(guarda);
    save.write(text.getText());
    save.close();
    as.jLabel.setText(nombre);
    as.dir = guarda.getPath();
    tabs.setTabComponentAt(tabs.getSelectedIndex(), as);
    JOptionPane.showMessageDialog(null,
         "El archivo se a guardado Exitosamente",
             "Información",JOptionPane.INFORMATION_MESSAGE);
    }
 }catch(IOException ex){
     System.out.println("error");
  }
    }//GEN-LAST:event_GuardarCActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
               try
        {
            JTabbedPaneCloseButton.CloseButtonTab as = (JTabbedPaneCloseButton.CloseButtonTab) tabs.getTabComponentAt(tabs.getSelectedIndex()).getComponentAt(0, 0);
            JScrollPane ax = (JScrollPane) as.tab;
            JTextPane text = (JTextPane) ax.getViewport().getComponent(0);
      
            
  if(as.dir !=null)
  {
    FileWriter  save = new FileWriter(as.dir);
    save.write(text.getText());
    save.close();
    JOptionPane.showMessageDialog(null,
         "El archivo se a guardado Exitosamente",
             "Información",JOptionPane.INFORMATION_MESSAGE);
    }
 }catch(IOException ex){
     System.out.println("error");
  }
    }//GEN-LAST:event_GuardarActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JButton Debugger;
    private javax.swing.JButton Ejecutar;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem GuardarC;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem Reemplazar;
    private javax.swing.JButton Reporte;
    private javax.swing.JMenuItem TErrores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
